### ISSUE TITLE
搜索后能否支持批量删除

### ISSUE THREAD

**Issue by zuohl** [trentlee0/mverything-plus#3]
目前只能选择单个以后删除

**Comment by trentlee0** [comment]
可以实现，请问有什么应用场景吗

**Comment by zuohl** [comment]
> 可以实现，请问有什么应用场景吗

有的,有时候需要删除某些重复文件,或者搜索某些后缀的文件,搜索以后希望能批量删除

**Comment by trentlee0** [comment]
> > 可以实现，请问有什么应用场景吗
> 
> 有的,有时候需要删除某些重复文件,或者搜索某些后缀的文件,搜索以后希望能批量删除

哦~~ 管理文件也是一个应用场景。下一个版本支持！
